CREATE TABLE ADMIN.TB_REPORT (
	REPORT_CODE VARCHAR(225) NOT NULL UNIQUE PRIMARY KEY,
	REPORT_NAME VARCHAR(225) NOT NULL
)

CREATE TABLE ADMIN.TB_CUST_REPORT (
	REPORT_CODE VARCHAR(225) NOT NULL,
	CUST_CD VARCHAR(225) NOT NULL,
	PRIMARY KEY (REPORT_CODE, CUST_CD),
	FOREIGN KEY (CUST_GB) REFERENCES ADMIN.TB_ITCUST(CUST_GB)
)

CREATE TABLE ADMIN.TB_CONSENT_TYPE (
	ID INT NOT NULL PRIMARY KEY,
	COLLECTION CLOB NOT NULL,
	DATA_USING CLOB NOT NULL,
	PROVIDING CLOB NOT NULL,
	CUST_GB VARCHAR(10) NOT NULL,
	FOREIGN KEY (CUST_GB) REFERENCES ADMIN.TB_ITCUST(CUST_GB)
)